---
- name: cleanup ml2/OVS agents services
  hosts: ovn-controllers
  roles:
    - cleanup

- name: Cleanup neutron servers
  hosts: neutron-api
  become: yes
  tasks:
    - name: set migration mode to False
      ini_file:
        path: /var/lib/config-data/puppet-generated/neutron/etc/neutron/plugins/ml2/ml2_conf.ini
        section: DEFAULT
        option: migration_mode
        value: False

    - name: Remove trunk bridge configuration from vif details
      shell: |
        galera_container=$(podman ps -a --format {% raw %}"{{.ID}}"{% endraw %} --filter "name=galera-bundle-podman")
        podman exec $galera_container mysql ovs_neutron -e "update ml2_port_bindings set vif_details='{\"connectivity\": \"l2\", \"port_filter\": true, \"ovs_hybrid_plug\": true, \"datapath_type\": \"system\", \"bridge_name\": \"br-int\"}' where vif_details like '%\"bridge_name\": \"tbr%';"
      when: ovn_central is defined

- name: cleanup Neutron ml2/OVS resources
  hosts: localhost
  roles:
    - delete-neutron-resources
